source 'https://rubygems.org'

gem 'activesupport'
gem 'capybara'
gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'pry'
gem 'site_prism'
gem 'selenium-webdriver'
gem 'chromedriver-helper'
gem 'require_all'
